# -*- coding: utf-8 -*-
"""Testmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CfEidpE9oeakMAoLxLj-qPKPP5L79Civ
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive/dataset/test | head
!ls /content/drive/MyDrive/dataset/train | head
!ls /content/drive/MyDrive/dataset/valid | head

!pip install ultralytics==8.3.5
!pip install onnxscript
from ultralytics import YOLO
import os
os.environ["WANDB_MODE"] = "disabled"
os.environ["WANDB_DISABLED"] = "true"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile data.yaml
# train: /content/drive/MyDrive/dataset/train/images
# val: /content/drive/MyDrive/dataset/valid/images
# 
# nc: 3
# names: ['lays', 'oreo', 'pepsi']

# Cargar modelo YOLOv11 small
model = YOLO('yolo11s.pt')

# Entrenar modelo small
model.train(
    data='data.yaml',
    epochs=100,
    imgsz=640,
    batch=16,
    name='train_small',
    project='runs_train',
    exist_ok=True
)

#Cargar modelo YOLOv11 Nano
model_n = YOLO('yolo11n.pt')

#Entrenar modelo nano
model_n.train(
    data='data.yaml',
    epochs=100,
    imgsz=640,
    batch=16,
    name='train_nano',
    project='runs_train',
    exist_ok=True
)

#Exportar onnx
# Small
best_s = 'runs_train/train_small/weights/best.pt'
model_s = YOLO(best_s)
model_s.export(format='onnx', imgsz=640, opset=11, dynamic=False)

# Nano
best_n = 'runs_train/train_nano/weights/best.pt'
model_n = YOLO(best_n)
model_n.export(format='onnx', imgsz=640, opset=11, dynamic=False)

import os, shutil, glob

# Rutas de exportación de YOLO
small_src = '/content/runs_train/train_small/weights/best.onnx'
nano_src  = '/content/runs_train/train_nano/weights/best.onnx'

# Verificación de existencia
print("Small existe:", os.path.exists(small_src))
print("Nano existe:", os.path.exists(nano_src))

# Renombrar para descarga
small_dst = 'model_small.onnx'
nano_dst  = 'model_nano.onnx'

shutil.copy(small_src, small_dst)
shutil.copy(nano_src, nano_dst)

print("Listo. Archivos preparados para descargar:")
print(small_dst)
print(nano_dst)

# Descargar y agregar al directorio principal
from google.colab import files
files.download(small_dst)
files.download(nano_dst)